version: '1.0.{build}'
image: Visual Studio 2017
branches:
  only:
  - master
init:
  # Good practise, because Windows line endings are different from Unix/Linux ones
  - cmd: git config --global core.autocrlf true
install:
  # Install repo specific stuff here
before_build:
  # Display .NET Core version
  - cmd: dotnet --version
  # Display minimal restore text
  - cmd: dotnet restore ./src/OwaspHeaders.Core.csproj --verbosity m
build_script:
  # output will be in ./src/bin/debug/netcoreapp1.1/publish
  - cmd: dotnet publish --configuration Production ./src/OwaspHeaders.Core.csproj
  # Create a NuGet packge for uploading
  - cmd: dotnet pack ./src/OwaspHeaders.Core.csproj --configuration Production --output nupkgs
after_build:
  # For once the build has completed
artifacts:
 - path: '\src\nupkgs\src.*.nupkg'
   name: NugetPackage
   type: Auto
test_script:
  # tests in here
  - cmd: dotnet restore ./tests/tests.csproj --verbosity m
  - cmd: cd tests
  - cmd: dotnet test
  - cmd: cd ..
clone_depth: 1
deploy:
 provider: Environment
 name: NuGet-OwaspHeaders
on_finish :
  # any cleanup in here